[WikipediaProcessor]
Path = "/data/WikiSearchData/bgwiki-20250120-pages-articles.xml"
CrawlLimit = 441386

[Crawler]
Domain = "https://bg.wikipedia.org"
CrawlLimit = 10
SeedURLs = ["https://bg.wikipedia.org"]

[FileDatabase]
Path = "/data/WikiSearchData/LMDB"
Size = "66571993000"

[USearchIndex]
Path = "/data/WikiSearchData/SemanticIndex/index.usearch"
dimension = 768

[FAISSIndex]
Path = "/data/WikiSearchData/SemanticIndex/index.faiss"
dimension = 768

[SpellChecker]
AffPath = "/data/WikiSearchData/SpellChecker/bg_BG_utf8.aff"
DicPath = "/data/WikiSearchData/SpellChecker/bg_BG_utf8.dic"
CustomDicPath = "/data/WikiSearchData/SpellChecker/custom_utf8.dic"

[Autocompletion]
WordCompletionDAWG = "/data/WikiSearchData/Autocompletion/word-completion.dawg"
NextWordDAWG = "/data/WikiSearchData/Autocompletion/next-word.dawg"

[Evaluator]
NumBatches = 5
QueriesPerBatch = 30
ResultsPerQuery = 20
InvertedResults = "/data/WikiSearchData/Stats/inverted_results.json"
SemanticResults = "/data/WikiSearchData/Stats/semantic_results.json"
InvertedMetrics = "/data/WikiSearchData/Stats/inverted_metrics.json"
SemanticMetrics = "/data/WikiSearchData/Stats/semantic_metrics.json"
