[WikipediaProcessor]
Path = "/data/WikiSearchData/bgwiki-20250120-pages-articles.xml"
CrawlLimit = 441386

[Crawler]
Domain = "https://bg.wikipedia.org"
CrawlLimit = 10
SeedURLs = ["https://bg.wikipedia.org"]

[FileDatabase]
Path = "/data/WikiSearchData/LMDB"
Size = "66571993000"

[USearchIndex]
Path = "/data/WikiSearchData/SemanticIndex/index.usearch"
dimension = 768

[FAISSIndex]
Path = "/data/WikiSearchData/SemanticIndex/index.faiss"
dimension = 768

[SpellChecker]
AffPath = "/data/WikiSearchData/Hunspell/bg_BG_utf.aff"
DicPath = "/data/WikiSearchData/Hunspell/bg_BG_utf.dic"

[Evaluator]
NumBatches = 5
QueriesPerBatch = 30
ResultsPerQuery = 20
InvertedResults = "/data/WikiSearchData/Stats/inverted_results.json"
SemanticResults = "/data/WikiSearchData/Stats/semantic_results.json"
InvertedMetrics = "/data/WikiSearchData/Stats/inverted_results.json"
SemanticMetrics = "/data/WikiSearchData/Stats/semantic_results.json"
