[WikipediaProcessor]
Path = "/data/WikiSearchData/bgwiki-20250120-pages-articles.xml"
CrawlLimit = 302500

[Crawler]
Domain = "https://bg.wikipedia.org"
CrawlLimit = 10
SeedURLs = ["https://bg.wikipedia.org"]

[Database]
Host = "localhost"
User = "wikisearch"
Password = "dih"
Name = "indexes"

[FileDatabase]
Path = "/data/WikiSearchData/LMDB"
Size = "66571993000"

[SemanticIndex]
Path = "/data/WikiSearchData/SemanticIndex/index.usearch"
dimension = 768

[SpellChecker]
AffPath = "/data/WikiSearchData/Hunspell/bg_BG_utf.aff"
DicPath = "/data/WikiSearchData/Hunspell/bg_BG_utf.dic"
